### ISSUE TITLE
[Bug]: Invalid or unsupported payment method when refunding via WooCommerce

### ISSUE THREAD

**Issue by JCZwier** [btcpayserver/woocommerce-greenfield-plugin#58]
### What is your BTCPay version?

I'm running BTCPay v1.13.7+83c948d12 (Altcoins)

### How did you deploy BTCPay Server?

I'm running BTCPay Server on a Docker instance

### What happened?

I get an error when I try to refund an order in WooCommerce that was paid using BTCPay. This only happens when I click 'Refund $... via BTCPay'. The error is below.

### How did you encounter this bug?

1. I enter the refund information in WooCommerce. 2. I click on 'Refund $... via BTCPay. 3. I get the error message that is pasted below.

### Relevant log output

```shell
Exception creating pull payment: Error during POST to https://example.com/api/v1/stores/6BSKiz4zRqydQXtaYo1jj3MLDgLdqC3ZjtEhR5YqU5Bt/pull-payments. Got response (422): [{"path":"PaymentMethods[1]","message":"Invalid or unsupported payment method"}]
```

### What browser do you use?

Firefox 132.0.1

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by JCZwier** [comment]
@pavlenex I'm using version 2.7.0.

**Comment by ndeet** [comment]
Hey @JCZwier tried to reproduce the error and found a different one but with BTCPay Server 2.0.

With BTCPay 1.13.x (which you seem to use) I could not reproduce your error. Your errors suggests that the payment methods passed to the pull payments endpoint is a nested array which is a bit weird. Can you give me more information about your setup so I can try to reproduce?
- What PHP version do you use?
- What settings do you have enabled on BTCPay Settings (on WooCommerce)
- What BTCPay Server version are you running?
- did you disable the original Payment method maybe? (in WooCommerce -> Settings -> Payments)?

Thank you.

**Comment by JCZwier** [comment]
@ndeet To answer your questions:

- On the WordPress server I'm using PHP version 8.1.18.
- The only setting I have enabled is 'Protect order status'.
- I'm running BTCPay Server v1.13.7+83c948d12 (Altcoins).
- The order was initially paid with BTCPay, and this payment option is enabled.

**Comment by ndeet** [comment]
was fixed in v2.7.0, closing

**Comment by JCZwier** [comment]
I'm not sure if I should create a new issue, but I'm still experiencing this bug. I'm now using version 2.7.2 of the plugin and BTCPay Server v2.2.1+790616d2a.

**Comment by ndeet** [comment]
Will take a look again although my tests showed no problems back then but maybe I will add more logging so we can understand the problem better.

**Comment by JCZwier** [comment]
Unfortunately I'm still getting the error. This is the the debug log when I try to refund a payment made using Bitcoin:

> 2026-03-28T10:40:25+00:00 Debug Refund: Order payment method: btcpaygf_default
> 2026-03-28T10:40:25+00:00 Debug Refund: Available payment methods: Array
> (
>     [0] => BTC_CHAIN
>     [1] => XMR_CHAIN
> )
> 2026-03-28T10:40:25+00:00 Debug Exception creating pull payment: Error during POST to https://example.com/api/v1/stores/6BSKiz4zRqydQXtaYo1jj3MLDgLdqC3ZjtEhR5YqU5Bt/pull-payments. Got response (422): [{"path":"PayoutMethods[1]","message":"Invalid or unsupported payment method"}]

**Comment by ndeet** [comment]
FYI, fixed in v2.7.5, issue was that XMR has no payout handler and was therefore making the request fail. So refund will be done in BTC (or any altcoin which implemented a payout handler)
